### ISSUE TITLE
See the history of deploy

### ISSUE THREAD

**Issue by davidebianchi** [mia-platform/miactl#16]
What are the last deployed version of my project in a specific environment?
And in all the environments?

We should display the information that answers to that

**Comment by fredmaggiowski** [comment]
I'm currently implementing this feature, but I've a few things that needs to be clarified:

 1. The SDK right now exposes a new interface `IDeploy' with a `GetHistory(string)` function, the string is the project id to search for. The deploy history API accepts different query parameters for filtering and pagination, shall we define a `GetHistory(DeployHistoryQuery)` where `DeployHistoryQuery` is a custom struct to be expanded in the future?

 2. on the command management side: i wanted to use keep the same approach used with the `getProject(*Factrory)` function but this command is a bit different, it requires an additional (required) flag `-p,--project` how shall we implement this in order to properly pave the way for future extensions?

**Comment by davidebianchi** [comment]
1. It could be interesting for further improvements of the client. But it's better a `GetHistory(DeployHistoryQuery)` or a `GetHistory(string, DeployHistoryQuery)` or something similar? The `projectId` is not a query, so it is not so correct the `DeployHistoryQuery` containing that.
2. For the `get` command the `-p` flag is not required, it is required for the `get deploy` or `get deploys` command. So I think that the flag should not be required but it is checked based on arguments.

**Comment by fredmaggiowski** [comment]
alright so

 1. I think that we can stick with `GetHistory(DeployHistoryQuery)`. Even though I agree that the `projectId` is not a query (as in query parameter of the projects API) as far as this command is concerned that's an implementation detail of the APIs, I think that's the best compromise between having to change the signature later (adding a second argument for the query) or having to deal with a useless argument right now.

2. so we could create a new command `deploy` and register it in the `get` command. The `deploy` command will check (and require) the `-p` flag (in the future it could take it from the context after a `use project` is used).

Usage of this command could be: `miactl get deploy history -p myProjectId` ?

**Comment by davidebianchi** [comment]
1. I agree
2. The subcommand does not convince me. I meant the command `get` with the argument `deploy`. Or `miactl get deployments -p myProjectId`?

**Comment by fredmaggiowski** [comment]
sounds good, I'll proceed this way

**Comment by fredmaggiowski** [comment]
I've finished the implementation and submitted PR #23
